src/NetcoreTraining.Web/ViewModels/CategoryViewModel.cs
namespace NetcoreTraining.Web.ViewModels
{
    public class CategoryViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

src/NetcoreTraining.Web/ViewModels/Post/PostDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetcoreTraining.Web.ViewModels.Post
{
    public class PostDetailsViewModel
    {
        public string Title { get; set; }
        public string Thumbnail { get; set; }
        public string ShortDescription { get; set; }
        public string Content { get; set; }
        public CategoryViewModel Category { get; set; }
    }
}

src/NetcoreTraining.Web/ViewModels/Post/PostListingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetcoreTraining.Web.ViewModels.Post
{
    public class PostListingViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Thumbnail { get; set; }
        public string ShortDescription { get; set; }
        public CategoryViewModel Category { get; set; }
    }
}

src/NetcoreTraining.Web/Components/HeaderCategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NetcoreTraining.Web.ViewModels;
using NetcoreTraining.Core.Entities;
using NetcoreTraining.Core.Interfaces.Repositories;

namespace NetcoreTraining.Web.Components
{
    public class HeaderCategoriesViewComponent : ViewComponent
    {
        private readonly IRepository<Category> _categoryRepository;
        public HeaderCategoriesViewComponent(IRepository<Category> categoryRepository) => _categoryRepository = categoryRepository;

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryRepository.GetAllAsync();
            var model = categories.Select(o => new CategoryViewModel
            {
                Id = o.Id,
                Name = o.Name
            });

            return View(model);
        }
    }
}

src/NetcoreTraining.Web/Components/SideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NetcoreTraining.Web.ViewModels;

namespace NetcoreTraining.Web.Components
{
    public class SideBarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

src/NetcoreTraining.Web/Controllers/OidcConfigurationController.cs
using Microsoft.AspNetCore.ApiAuthorization.IdentityServer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace NetcoreTraining.Web.Controllers
{
    public class OidcConfigurationController : Controller
    {
        private readonly ILogger<OidcConfigurationController> logger;

        public OidcConfigurationController(IClientRequestParametersProvider clientRequestParametersProvider, ILogger<OidcConfigurationController> _logger)
        {
            ClientRequestParametersProvider = clientRequestParametersProvider;
            logger = _logger;
        }

        public IClientRequestParametersProvider ClientRequestParametersProvider { get; }

        [HttpGet("_configuration/{clientId}")]
        public IActionResult GetClientRequestParameters([FromRoute]string clientId)
        {
            var parameters = ClientRequestParametersProvider.GetClientParameters(HttpContext, clientId);
            return Ok(parameters);
        }
    }
}

src/NetcoreTraining.Web/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using NetcoreTraining.Core.Interfaces.Sevices;
using NetcoreTraining.Web.ViewModels;
using NetcoreTraining.Web.ViewModels.Post;
using System.Linq;
using System.Threading.Tasks;

namespace NetcoreTraining.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        public async Task<ActionResult> ListPost()
        {
            var posts = await _postService.ListPostByPageAsync(2, 1);

            var model = posts.Select(o => new PostListingViewModel
            {
                Id = o.Id,
                Title = o.Title,
                Thumbnail = o.Thumbnail,
                ShortDescription = o.ShortDescription,
                Category = new CategoryViewModel
                {
                    Id = o.Category.Id,
                    Name = o.Category.Name,
                },
            });

            return View(model);
        }

        [Route("{id}")]
        [Route("Post/{id}")]
        public async Task<ActionResult> Details(int id)
        {
            var post = await _postService.GetPostDetailById(id);

            if (post == null)
            {
                return RedirectToAction(nameof(ListPost));
            }

            var model = new PostDetailsViewModel
            {
                Title = post.Title,
                Thumbnail = post.Thumbnail,
                ShortDescription = post.ShortDescription,
                Category = new CategoryViewModel
                {
                    Id = post.Category.Id,
                    Name = post.Category.Name
                },
                Content = post.Content,
            };

            return View(model);
        }
    }
}

src/NetcoreTraining.Web/Controllers/WeatherForecastController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace NetcoreTraining.Web.Controllers
{
    [Authorize]
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}

src/NetcoreTraining.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace NetcoreTraining.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/NetcoreTraining.Web/Views/Post/Details.cshtml
@model NetcoreTraining.Web.ViewModels.Post.PostDetailsViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="kotha-default-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <article class="single-blog">
                    <div class="post-thumb">
                        <img src="@Model.Thumbnail" alt="@Model.Thumbnail">
                    </div>
                    <div class="post-content">
                        <div class="entry-header text-center text-uppercase">
                            <a href="" class="post-cat">@Model.Category.Name</a>
                            <h2>@Model.Title</h2>
                        </div>
                        <div class="entry-content">
                            <p class="post-details-description">@Model.ShortDescription</p>
                            @Html.Raw(@Model.Content)
                        </div>

                        <div class="post-meta">
                            <ul class="pull-left list-inline author-meta">
                                <li class="author">By <a href="#">Jennifer </a></li>
                                <li class="date"> On February 12, 2017</li>
                            </ul>
                            <ul class="pull-right list-inline social-share">
                                <li><a href=""><i class="fa fa-facebook"></i></a></li>
                                <li><a href=""><i class="fa fa-twitter"></i></a></li>
                                <li><a href=""><i class="fa fa-pinterest"></i></a></li>
                                <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                                <li><a href=""><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </article>
                <div class="comment-area">
                    <div class="comment-heading">
                        <h3>3 Thoughts</h3>
                    </div>
                    <div class="single-comment">
                        <div class="media">
                            <div class="media-left text-center">
                                <a href=""><img class="media-object" src="assets/images/reply-1.jpg" alt=""></a>
                            </div>
                            <div class="media-body">
                                <div class="media-heading">
                                    <h3 class="text-uppercase">
                                        <a href="">John Smith</a>
                                    </h3>
                                </div>
                                <p class="comment-date">
                                    December, 02, 2017 at 5:57 PM
                                </p>
                                <p class="comment-p">
                                    Nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sdiam
                                    voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
                                    gubergren, no sea takimata sanctus est.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="single-comment">
                        <div class="media">
                            <div class="media-left text-center">
                                <a href=""> <img class="media-object" src="assets/images/reply-3.jpg" alt=""></a>
                            </div>
                            <div class="media-body">
                                <div class="media-heading">
                                    <h3 class="text-uppercase">
                                        <a href="">Ricard Goff</a>
                                    </h3>
                                </div>
                                <span class="comment-date"> 5 hours ago</span>
                                <p class="comment-p">
                                    Amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidu labore et
                                    dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et usto duo
                                    dolores et ea rebum.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <!--leave comment-->
                <div class="leave-comment">
                    <h4>Leave a reply</h4>
                    <form class="form-horizontal contact-form" method="post" action="#">
                        <div class="form-group">
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Name" required="">
                            </div>
                            <div class="col-md-6">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email" required="">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input type="text" class="form-control" id="subject" name="subject" placeholder="Website url">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea class="form-control" rows="6" name="message" placeholder="Write Massage" required=""></textarea>
                            </div>
                        </div>
                        <button type="submit" class="btn send-btn">Post Comment</button>
                    </form>
                </div>
            </div>

            <div class="col-sm-4">
                <vc:side-bar></vc:side-bar>
            </div>
        </div>
    </div>
</div>

src/NetcoreTraining.Web/Views/Post/ListPost.cshtml
@model IEnumerable<NetcoreTraining.Web.ViewModels.Post.PostListingViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="kotha-default-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                @foreach (var post in Model)
                {
                    <article class="single-blog">
                        <div class="post-thumb">
                            <a asp-controller="Post" asp-action="Details" asp-route-id="@post.Id"><img src="@post.Thumbnail" alt="" id="exifviewer-img-2"></a>
                        </div>
                        <div class="post-content">
                            <div class="entry-header text-center text-uppercase">
                                <a href="#" class="post-cat">@post.Category.Name</a>
                                <h2><a asp-controller="Post" asp-action="Details" asp-route-id="@post.Id">@post.Title</a></h2>
                            </div>
                            <div class="entry-content">
                                <p>@post.ShortDescription</p>
                            </div>
                            <div class="continue-reading text-center text-uppercase">
                                <a asp-controller="Post" asp-action="Details" asp-route-id="@post.Id">Continue Reading</a>
                            </div>
                            <div class="post-meta">
                                <ul class="pull-left list-inline author-meta">
                                    <li class="author">By <a href="#">Author </a></li>
                                    <li class="date">On October 13, 2017</li>
                                </ul>
                                <ul class="pull-right list-inline social-share">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </article>

                }
                <div class="post-pagination  clearfix">
                    <ul class="pagination text-left">
                        <li class="active"><a href="http://demo.shapedtheme.com/kotha-pro-html/#">1</a></li>
                        <li><a href="http://demo.shapedtheme.com/kotha-pro-html/#">2</a></li>
                        <li><a href="http://demo.shapedtheme.com/kotha-pro-html/#">3</a></li>
                        <li><a href="http://demo.shapedtheme.com/kotha-pro-html/#">4</a></li>
                        <li><a href="http://demo.shapedtheme.com/kotha-pro-html/#"><i class="fa fa-angle-double-right"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4">
                <vc:side-bar></vc:side-bar>
            </div>
        </div>
    </div>
</div>

src/NetcoreTraining.Web/Views/Shared/Components/HeaderCategories/Default.cshtml
@model IEnumerable<NetcoreTraining.Web.ViewModels.CategoryViewModel>

    <ul class="nav navbar-nav text-uppercase pull-right">
        @{
            int numberOfShowCategories = 5;
            foreach (var cateory in Model.Take(numberOfShowCategories))
            {
                <li><a href="#@cateory.Id">@cateory.Name</a></li>
            }

            if (Model.Count() > numberOfShowCategories)
            {
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Other categories</a>
                    <ul class="dropdown-menu">
                        @foreach (var cateory in Model.Skip(numberOfShowCategories))
                        {
                            <li><a href="#@cateory.Id">@cateory.Name</a></li>
                        }
                    </ul>
                </li>
            }
        }
    </ul>

src/NetcoreTraining.Web/Views/Shared/Components/SideBar/Default.cshtml
<div class="kotha-sidebar">
    <aside class="widget about-me-widget  text-center">
        <div class="about-me-content">
            <div class="about-me-img">
                <img src="~/images/netcore.png" alt="" class="img-me img-circle" id="exifviewer-img-1" exifid="1762574682" oldsrc="~/images/netcore.png">
                <h2 class="text-uppercase">NetCore Blog</h2>
                <p>
                    This is some description about the blog with links to social network under. Lorem ipsum dolor sit met....
                </p>
            </div>
        </div>
        <div class="social-share">
            <ul class="list-inline">
                <li><a target="_blank" class="s-facebook" href="https://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
                <li><a target="_blank" class="s-twitter" href="https://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
                <li><a target="_blank" class="s-google-plus" href="https://www.theguardian.com/technology/2019/feb/01/closure-google-plus-everything-you-need-to-know"><i class="fa fa-google-plus"></i></a></li>
                <li><a target="_blank" class="s-linkedin" href="https://www.linkedin.com"><i class="fa fa-linkedin"></i></a></li>
                <li><a target="_blank" class="s-instagram" href="https://www.instagram.com"><i class="fa fa-instagram"></i></a></li>
            </ul>
        </div>
    </aside>
    <aside class="widget latest-post-widget">
        <h2 class="widget-title text-uppercase text-center">Latest Posts</h2>
        <ul>
            <li class="media">
                <div class="media-left">
                    <a href="http://demo.shapedtheme.com/kotha-pro-html/#" class="popular-img">
                        <img src="~/images/recent-1.jpg" alt="">
                    </a>
                </div>
                <div class="latest-post-content">
                    <h2 class="text-uppercase"><a href="http://demo.shapedtheme.com/kotha-pro-html/#">A Marine Dive From Sky</a></h2>
                    <p>May 27, 2017</p>
                </div>
            </li>
            <li class="media">
                <div class="media-left">
                    <a href="http://demo.shapedtheme.com/kotha-pro-html/#" class="popular-img">
                        <img src="~/images/recent-2.jpg" alt="">
                    </a>
                </div>
                <div class="latest-post-content">
                    <h2 class="text-uppercase"><a href="http://demo.shapedtheme.com/kotha-pro-html/#">Small Meeting Room</a></h2>
                    <p>April 27, 2017</p>
                </div>
            </li>
            <li class="media">
                <div class="media-left">
                    <a href="http://demo.shapedtheme.com/kotha-pro-html/#" class="popular-img">
                        <img src="~/images/recent-3.jpg" alt="">
                    </a>
                </div>
                <div class="latest-post-content">
                    <h2 class="text-uppercase"><a href="http://demo.shapedtheme.com/kotha-pro-html/#">Selfie from the beach point</a></h2>
                    <p>April 20, 2017</p>
                </div>
            </li>
            <li class="media">
                <div class="media-left">
                    <a href="http://demo.shapedtheme.com/kotha-pro-html/#" class="popular-img">
                        <img src="~/images/recent-4.jpg" alt="">
                    </a>
                </div>
                <div class="latest-post-content">
                    <h2 class="text-uppercase"><a href="http://demo.shapedtheme.com/kotha-pro-html/#">Gather Some Artist Pencils.</a></h2>
                    <p>May 27, 2017</p>
                </div>
            </li>
        </ul>
    </aside>
    <aside class="widget add-widget">
        <h2 class="widget-title text-uppercase text-center">Advertisement</h2>

        <div class="add-image">
            <a href="http://demo.shapedtheme.com/kotha-pro-html/"><img src="~/images/add-image.jpg" alt=""></a>
        </div>
    </aside>
</div>

src/NetcoreTraining.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] - NetCore Blog</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700,700i%7cOswald:300,400,500,600,700%7cPlayfair+Display:400,400i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/slick-theme.css">
    <link rel="stylesheet" href="~/css/slick.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <header class="kotha-menu marketing-menu">
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="menu-content">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <a class="navbar-brand" asp-controller="Post" asp-action="ListPost">NetCore Blog</a>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <vc:header-categories></vc:header-categories>
                    </div>
                    <div class="show-search">
                        <form role="search" method="get" id="searchform" action="http://demo.shapedtheme.com/kotha-pro-html/#">
                            <input type="text" placeholder="Search and hit enter..." name="s" id="s">
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->
        </nav>
    </header>
    @RenderBody();
    <footer>
        <div class="container-fluid text-center ft-copyright">
            <p>© 2020 <a href="#">Netcore Blog </a> - Designed with <i class="fa fa-heart"></i> by <a href="https://gitlab.com/tungm">tungm</a></p>
        </div>
    </footer>
    <!--//Script//-->
    <script src="~/js/jquery-1.12.4.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/slick.min.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>